### PR TITLE
Enable debug logging when running via Gradle

### PR DESCRIPTION
**Pull request by intgr**
### Contributor checklist

- [x] I am using the provided [codeStyleConfig.xml](https://github.com/leinardi/mypy-pycharm/blob/release/.idea/codeStyles/codeStyleConfig.xml)
- [x] I have tested my contribution on these versions of PyCharm/IDEA:
 * PyCharm Community 2021.2.3
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit 
      using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-using-keywords/)

----------

### Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | ✳️ Other |

### CODE REVIEW

**Comment by leinardi** [comment]
Hi @intgr, could you telling me more about this PR? I tried the branch but I can't find where the logs are shown...

**Comment by intgr** [comment]
You can find it with "Show Log in [x]" in the Help menu. ([x] differs depending on OS)

image

**Comment by leinardi** [comment]
Mmm, I still don't get it: what is this line doing exactly?
```
systemProperties.put("idea.log.debug.categories", "#com.leinardi.pycharm.mypy")
```

I'm pretty sure the logs were showing in that file even without this change...

**Comment by intgr** [comment]
By default, only messages with level INFO or higher appear in logs. DEBUG messages were hidden.

This makes DEBUG messages from mypy plugin classes show up in logs.

**Pull request merged**
