### PR TITLE
Update deprecated notifications API usage

### PR DESCRIPTION
**Pull request by intgr**
### Contributor checklist

- [x] I am targeting the `master` branch (and **not** the `release` branch)
- [x] I am using the provided [codeStyleConfig.xml](https://github.com/leinardi/mypy-pycharm/blob/release/.idea/codeStyles/codeStyleConfig.xml)
- [x] I have tested my contribution on these versions of PyCharm/IDEA:
 * PyCharm Community 2021.3
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit 
      using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-using-keywords/)

----------

### Description
* Notification groups are now defined in plugin.xml
* `createNotification()` method with over 4 arguments are deprecated
* Deleted unused methods in `Notifications` & fixed IntelliJ inspections

Docs: https://plugins.jetbrains.com/docs/intellij/notifications.html#top-level-notifications-balloons

### Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :hammer: Refactoring  |

### CODE REVIEW

**Review by leinardi — APPROVED** [review]
LGTM :+1:

**Comment by leinardi** [comment]
Hi @intgr, looks like this changes break compatibility with older version of IDEA:
image

To keep them we should raise the min version from `201.8743` to `212.5712`.

What do you think?

**Comment by intgr** [comment]
Ah this isn't something I considered, maybe I should have.

Personally, I would just bump the minimum version and not worry about compatibility. If users don't want to upgrade to newer IDE versions, maybe they shouldn't expect to be able to update plugins either -- they can still use the old plugin version. Similar to how we did in https://github.com/leinardi/mypy-pycharm/pull/77#issuecomment-987157715

Although 212.5712 corresponds to IDEA 2021.2.4, which is still quite new.

Perhaps add a message to the plugin's description or release notes about this: if there are any users who need this plugin in older IDE versions, they can open an issue and we can consider reversing this policy.

**Comment by intgr** [comment]
By the way, you can change the minimum version in the JetBrains Marketplace website directly.

There is no need to make a new release to change it.

**Comment by leinardi** [comment]
Interesting! I'll try :)

**Pull request merged**
