### PR TITLE
fix: ActionUpdateThread deprecation warnings

### LINKED ISSUE #120: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon
### Step 1: Are you in the right place?
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
```
PyCharm 2024.1 (Community Edition)
Build #PC-241.14494.241, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.14494.240)
  some.awesome (1.15)
  com.intellij.ideolog (222.3.2.0)
  com.jetbrains.space (241.14494.150)
  org.sonarlint.idea (10.2.0.77238)
  com.leinardi.pycharm.mypy (0.16.2)
  com.leinardi.pycharm.pylint (0.16.2)
```

#### Steps to reproduce:

  1. Open PyCharm 2024.1 (Community Edition)

#### Observed Results:

  * Error message:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.leinardi.pycharm.mypy.actions.ClearAll' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.leinardi.pycharm.mypy]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```
  

#### Expected Results:

  * No error message / no usage of deprecated methods

### PR DESCRIPTION
**Pull request by dw-0**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/leinardi/mypy-pycharm/blob/release/.github/CONTRIBUTING.md) to this project
- [x] I have read [the code of conduct](https://github.com/leinardi/mypy-pycharm/blob/release/.github/CODE_OF_CONDUCT.md) to this project

### Contributor checklist

- [x] I am targeting the `master` branch (and **not** the `release` branch)
- [x] I am using the provided [codeStyleConfig.xml](https://github.com/leinardi/mypy-pycharm/blob/release/.idea/codeStyles/codeStyleConfig.xml)
- [x] I have tested my contribution on these versions of PyCharm/IDEA:
 * IntelliJ IDEA 2024.2.3
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit 
      using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-using-keywords/)

----------

### Description
This PR fixes the ActionUpdateThread deprecation warnings appearing in newer IntelliJ IDEA IDEs while using this Plugin.
During build of the project, there are still some other deprecation warnings. Those were not fixed in the scope of this PR.

I decided to target a 2023 PyCharm version, because any 2024 versions would require usage of the `org.jetbrains.intellij.platform` plugin version `2.1.0` which would require even more refactorings i was not comfortable with doing them yet. So i decided to bump the `org.jetbrains.intellij` to the latest version `1.17.4`.

### Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

### Related Issue
Closes #120

### CODE REVIEW

**Comment by leinardi** [comment]
Hi @dw-0, thank you for your contribution and for addressing the ActionUpdateThread deprecation warnings! I appreciate the effort you've put into it.

Before I proceed with reviewing the PR, I’d like to kindly ask if you could rebase your branch on top of my old-edt branch. I’ve been working on similar changes there, including fixes for some deprecation warnings, which might overlap with what you’ve tackled. Rebasing will make it easier for me to identify what specifically resolves the issue that I wasn’t able to fix in my branch.

**Comment by dw-0** [comment]
There you go.
I had to build the project twice before i was able to run buildPlugin for some reason, no idea why.
I guess you simply did not add the overwrite to all classes which require the overwrite :)

**Comment by leinardi** [comment]
Hey thanks again, I tried your changes and I can confirm that it seems to fix the issue!
I just have one question before merging it: I saw that you sometimes use `ActionUpdateThread.EDT` and sometimes use `ActionUpdateThread.BGT`, can you tell me which logic are you applying between one or the other?

**Comment by leinardi** [comment]
Thank you for the explanation and I think that the use of the BGT is actually what is properly fixing the issue because, if you look at my changes carefully, you'll see that I always applied the EDT via the BaseAction, but I was then getting some `Slow operations are prohibited on EDT` errors due to the use of EDT instead of BGT: https://github.com/leinardi/mypy-pycharm/issues/120#issuecomment-2301869943

Final question, do you mind if I add this to the changelog?
```
- Fixed #120: Defined action update thread for actions (thanks @dw-0 for the help!)
```

**Comment by dw-0** [comment]
> Thank you for the explanation and I think that the use of the BGT is actually what is properly fixing the issue because, if you look at my changes carefully, you'll see that I always applied the EDT via the BaseAction, but I was then getting some `Slow operations are prohibited on EDT` errors due to the use of EDT instead of BGT: [#120 (comment)](https://github.com/leinardi/mypy-pycharm/issues/120#issuecomment-2301869943)
Ah, yeah that makes sense now! I removed the overwrite from the BaseAction again, because i thought that adding it explicitly in each action makes more sense and a developer has to really think about which action should be handled in which thread. You could of course keep the overwrite in the BaseAction but then you have to overwrite it AGAIN in some actions where you need the other thread. Thats kind of odd.

> Final question, do you mind if I add this to the changelog?
> 
> ```
> - Fixed #120: Defined action update thread for actions (thanks @dw-0 for the help!)
> ```
Sure! Feel free to do so :)

**Comment by leinardi** [comment]
> I removed the overwrite from the BaseAction again, because i thought that adding it explicitly in each action makes more sense and a developer has to really think about which action should be handled in which thread.

I would 100% agree with you if the override was for an abstract method but, unfortunately, it is not abstract and it will build totally fine if the developer completely forget to override it and, since the majority of actions are EDT and you still get errors for slow threads on EDT, I would still prefer to add the override to the BaseAction, just to avoid some code duplication. Hope you don't mind.

**Comment by dw-0** [comment]
Okay i didn't view at it from this perspective, you are right there. I don't mind if you add it back to the BaseAction class then. Its safer, as you explained.

**Pull request merged**
